version: "23.0.5"
services:
  api:
    depends_on:
      - postgres
    build: .
    ports:
      - 8000:8000
    env_file:
      - shiv_trading_backend/.env
  postgres:
    image: postgres
    env_file:
      - shiv_trading_backend/.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data/
volumes:
  postgres-db: